In [1]:
import pandas as pd
import os

# Prompt user to enter file name
file_name = input("Enter the file name: ").lower() + '.csv'

# Check if file exists
if not os.path.isfile(file_name):
    print("File not found, please enter the correct file name")
else:
# the try except block
    try:
        # Load CSV file into a pandas DataFrame
        df = pd.read_csv(file_name)
    except csv.Error:
        # Handle errors that occur while reading the CSV file
        print("An error occurred while reading the file")

Enter the file name: airbnb_uk_2022

In [32]:
# Identifying the top 10 most popular amenities or features that Airbnb hosts provide to customers

# Create an empty dictionary to store amenities and their counts
amenities_counts = {}

# Loop through each amenities list in the 'amenities' column of the dataframe
for amenities_list in df['amenities']:
    # Clean up the amenities list by removing unnecessary characters and splitting into separate amenities
    amenities = amenities_list.replace('[', '').replace(']', '').replace('"', '').replace("'", "").replace(" ", "").split(',')
    # Loop through each amenity in the cleaned up amenities list
    for amenity in amenities:
        # Increment the count for the amenity in the amenities_counts dictionary
        if amenity in amenities_counts:
            amenities_counts[amenity] += 1
        # Add the amenity to the amenities_counts dictionary with a count of 1 if it doesn't exist
        else:
            amenities_counts[amenity] = 1

# Sort the amenities_counts dictionary items by count in descending order and get the top 10
top_amenities = sorted(amenities_counts.items(), key=lambda x: x[1], reverse=True)[:10]

# Print the top 10 amenities with their counts
print("Top 10 amenities:")
for i, amenity in enumerate(top_amenities, start=1):
    print(f"{i}. {amenity[0]}: {amenity[1]}")

Top 10 amenities:
1. Smokealarm: 7981
2. Kitchen: 7700
3. Essentials: 7538
4. Wifi: 7358
5. Iron: 6710
6. Hangers: 6651
7. Hotwater: 6610
8. Longtermstaysallowed: 6607
9. Dishesandsilverware: 6415
10. Hairdryer: 6272

# note: while making the video i will say that i tried to use the enumerate function to display the numbers in the second top amenities but i could not find a way to do it

In [36]:
# Prompt user to enter the number of top amenities they want to see
top_amenities = int(input("Enter the number of top amenities you want to see: "))

# Create a dictionary to store the counts of each amenity
amenities_counts = {}

# Loop through each row of the 'amenities' column
for amenities_list in df['amenities']:
    # Remove special characters from the amenities string
    amenities = amenities_list.replace('[', '').replace(']', '').replace('"', '').replace("'", "").replace(" ", "").split(',')
    # Loop through each amenity and add it to the counts dictionary
    for amenity in amenities:
        if amenity in amenities_counts:
            amenities_counts[amenity] += 1
        else:
            amenities_counts[amenity] = 1

# Sort the amenities by count in descending order
sorted_amenities = sorted(amenities_counts.items(), key=lambda x: x[1], reverse=True)

# Print the top n amenities as specified by the user
print(f"Top {top_amenities} amenities:")
for i in range(top_amenities):
    print(f"- {sorted_amenities[i][0]}: {sorted_amenities[i][1]}")

Enter the number of top amenities you want to see: 6
Top 6 amenities:
- Smokealarm: 7981
- Kitchen: 7700
- Essentials: 7538
- Wifi: 7358
- Iron: 6710
- Hangers: 6651

In [37]:
# Task 2: Analyse the average price of stay in each location
avg_price_by_location = df.groupby('host_location')['price'].mean()
print("Average price by location:")
for location, avg_price in avg_price_by_location.items():
    print(f"{location}: {avg_price:.2f}")

Average price by location:
Aberdeen: 152.33
Aberystwyth: 64.00
Addington: 124.00
Ascot: 300.00
Ashford: 65.38
Ashtead: 104.00
Ashurstwood: 239.00
Avebury: 90.00
Aveley: 72.00
Aynho: 380.00
Banbury: 110.00
Banstead: 75.75
Barking: 64.00
Barnet: 54.00
Basildon: 159.00
Bath: 167.00
Beckenham: 158.00
Begbroke: 263.00
Belfast: 136.00
Belvedere: 49.00
Bexley: 78.75
Bexleyheath: 82.33
Binton: 100.00
Birmingham: 90.00
Bishop's Stortford: 200.00
Bondleigh: 205.00
Borehamwood: 35.00
Boughton Monchelsea: 200.00
Bournemouth: 110.67
Bradley Stoke: 119.00
Brecon: 214.00
Brent: 36.00
Brentford: 69.14
Brentwood: 115.00
Bricket Wood: 561.00
Bridford: 145.00
Brighton: 146.78
Bristol: 75.88
Bromley: 44.80
Brookwood: 110.00
Buckhurst Hill: 178.50
Burnham: 160.00
Burntwood: 150.00
Buscot: 700.00
Bushey: 44.00
Butterleigh: 638.00
Buxton: 107.00
Cambridge: 283.00
Camden Town: 57.00
Canterbury: 131.00
Capel Isaac: 200.00
Cardiff: 108.50
Carshalton: 56.75
Caterham: 72.00
Chaldon: 70.00
Chelmsford: 136.67
Chertsey: 132.00
Chester: 236.00
Chestfield: 218.00
Chichester: 200.00
Chiddingfold: 350.00
Chigwell: 38.00
Child Okeford: 331.00
Chislehurst: 175.00
Chorleywood: 140.00
Cirencester: 292.00
Claygate: 69.50
Colchester: 315.00
College Town: 150.00
Cookham: 135.50
Cothelstone: 150.00
Coulsdon: 54.00
Coventry: 154.00
Cowdenbeath: 90.00
Coxley: 120.00
Cranbrook: 439.00
Crediton: 32.00
Crockenhill: 137.00
Crockerton: 360.00
Crostwick: 300.00
Croydon: 77.07
Cuffley: 35.00
Dagenham: 91.29
Dartford: 179.57
Delph: 511.00
Denham: 116.00
Denton: 85.00
Downe: 76.00
Dundee: 156.50
East Molesey: 148.56
Eastbourne: 250.00
Edgware: 90.00
Edinburgh: 155.82
Egerton: 185.00
Elstree: 168.00
Enfield: 68.14
Epsom: 104.50
Esher: 94.00
Ewell: 150.00
Exeter: 146.00
Fairwarp: 52.00
Farnborough: 180.00
Farnham: 142.00
Feltham: 110.33
Fetcham: 178.00
Findon: 80.00
Frittenden: 250.00
Frome: 110.00
Fyfield: 256.00
Gamston: 145.00
Giffnock: 239.00
Gillingham: 100.00
Glasgow: 75.00
Gloucester: 148.00
Goff's Oak: 65.00
Great Chesterford: 184.00
Great Milton: 325.00
Great Missenden: 379.00
Great Waltham: 37.00
Green Tye: 125.00
Greenford: 58.00
Gretton: 130.00
Guildford: 355.20
Guiseley: 131.00
Hackney: 64.00
Hagley: 156.00
Hammersmith: 140.00
Hampreston: 450.00
Hampton: 134.17
Hampton Hill: 40.00
Hampton Wick: 105.00
Hamstead Marshall: 55.00
Harefield: 80.00
Harlington: 85.00
Harrogate: 280.00
Harrow: 78.15
Hartland: 200.00
Hayes: 36.33
Hayle: 99.00
Hebden Bridge: 115.00
Herne Bay: 120.00
Hessle: 175.00
High Wycombe: 244.00
Hinton Ampner: 241.00
Hordle: 275.00
Horley: 190.00
Hornchurch: 97.67
Horsham: 800.00
Hounslow: 44.33
Hove: 107.00
Huddersfield: 61.00
Hull: 314.00
Huntington: 90.00
Hurst Green: 41.00
Hurstpierpoint: 160.00
Ickenham: 48.33
Ilford: 42.75
Instow: 150.00
Isleworth: 65.75
Islington: 50.00
Kendal: 85.00
Kensington: 75.00
Kingston upon Thames: 119.65
Kirdford: 139.00
Langley: 386.00
Leeds: 89.00
Leicester: 133.00
Linchmere: 254.00
Lindfield: 212.00
Linkenholt: 375.00
Little Ann: 228.00
Liverpool: 170.00
London: 149.69
Long Ditton: 115.00
Longford: 140.00
Loughborough: 139.00
Loughton: 80.00
Ludlow: 220.00
Luton: 71.50
Lymm: 80.00
Lyng: 380.00
Maidstone: 139.00
Manchester: 159.42
Margate: 195.00
Marlow: 193.00
Martlesham: 200.00
Mells: 65.00
Milton Keynes: 40.50
Mitcham: 33.75
Molesey: 140.00
Monxton: 350.00
Morden: 83.75
New Barnet: 157.75
New Malden: 104.17
Newbury: 138.00
Newcastle Upon Tyne: 140.00
Newcastle upon Tyne: 150.00
Newgale: 65.00
Northaw: 90.00
Northolt: 84.00
Northwood: 60.40
Norwich: 157.50
Nottingham: 95.00
Oakley: 170.00
Old Coulsdon: 39.00
Orpington: 84.91
Oxford: 143.62
Paddington: 123.00
Perivale: 49.33
Pinner: 60.00
Poole: 140.50
Potters Bar: 97.50
Prestwich: 45.00
Purleigh: 309.00
Purley: 140.00
Rainham: 30.00
Reading: 161.50
Reigate: 91.00
Richmond: 203.44
Rickmansworth: 72.40
Ripponden: 200.00
Roade: 303.00
Romford: 115.09
Royal Leamington Spa: 171.00
Royal Tunbridge Wells: 250.00
Ruddington: 103.00
Ruislip: 103.00
Rye: 850.00
Saint Albans: 155.00
Saint Leonards: 119.67
Saint Mary Bourne: 95.00
Salisbury: 67.50
Sandhurst: 85.00
Scawby: 250.00
Scotland: 172.25
Selsey: 159.00
Sevenoaks: 198.33
Shaftesbury: 85.00
Sheffield: 280.00
Shillington: 100.00
Shoreham-by-Sea: 2357.50
Shrivenham: 155.00
Sidcup: 49.50
Skewen: 100.00
Slough: 181.00
Solihull: 163.50
Sompting: 55.00
South Croydon: 41.00
South Littleton: 200.00
South Ockendon: 44.50
Southall: 85.00
Southampton: 150.00
Southend-on-Sea: 131.25
St Albans: 66.00
St. Ives: 120.00
Staines-upon-Thames: 31.00
Stanwell: 62.50
Stapleford Abbotts: 85.00
Stelling Minnis: 125.00
Stirling: 508.00
Stockport: 267.00
Stratford: 54.00
Stratford-upon-Avon: 70.00
Sunbury: 120.00
Sunbury-on-Thames: 57.33
Sunninghill: 200.00
Surbiton: 116.57
Sutton: 82.78
Sutton Weaver: 144.00
Swansea: 250.00
Taplow: 161.00
Tatsfield: 75.00
Teddington: 75.75
Thames Ditton: 143.57
Thetford: 220.00
Thornton Heath: 45.67
Tibbermore: 350.00
Tilton on the Hill: 219.00
Tolleshunt D'Arcy: 130.00
Totnes: 131.00
Truro: 202.50
Tunworth: 110.00
Twickenham: 98.00
Upminster: 200.00
Upper Basildon: 95.00
Uxbridge: 87.25
Wales: 274.33
Wallington: 55.67
Waltham Abbey: 62.33
Walton-on-Thames: 127.00
Warlingham: 119.00
Watford: 174.00
Welling: 51.67
Wembley: 184.20
West Hyde: 52.00
West Molesey: 53.33
West Pennard: 211.00
West Wittering: 420.00
Westerham: 69.00
Weston Rhyn: 132.00
Weybridge: 153.00
Winchester: 142.00
Windsor: 303.50
Winterbourne: 139.00
Wolverton: 87.00
Woodford: 65.33
Worcester Park: 37.00
Wraysbury: 76.00
York: 250.00

In [4]:
# Prompt user to enter location
location = input("Enter location: ").lower()

try:
    # Filter the dataframe to include only the specified location
    location_df = df.loc[df['host_location'].str.contains(location, case=False)]

    # Calculate the average price for the specified location
    avg_price = location_df['price'].mean()

    # Print the average price for the specified location
    print(f"The average price for stays in {location.capitalize()} is £{avg_price:.2f} per night.")

except KeyError:
    print(f"Error: 'host_location' column not found in dataset. Please check and try again.")

except ValueError:
    print(f"Error: no data found for location '{location}'. Please check the spelling and try again.")

Enter location: london
The average price for stays in London is £149.69 per night.

In [14]:
# Calculate the average review scores rating by location
avg_rating_by_location = df.groupby('host_location')['review_scores_rating'].mean()

# Print the average review scores rating by location
print("Average review scores rating by location")
for host_location, avg_rating in avg_rating_by_location.items():
    print(f"{host_location}: {avg_rating:.1f}")

Average review scores rating by location
Aberdeen: 4.3
Aberystwyth: 4.8
Addington: 4.7
Ascot: 4.9
Ashford: 4.6
Ashtead: 5.0
Ashurstwood: 4.9
Avebury: 4.8
Aveley: 5.0
Aynho: 5.0
Banbury: 5.0
Banstead: 4.7
Barking: 4.7
Barnet: 4.7
Basildon: 4.7
Bath: 4.9
Beckenham: 5.0
Begbroke: 4.8
Belfast: 4.7
Belvedere: 5.0
Bexley: 5.0
Bexleyheath: 4.6
Binton: 4.8
Birmingham: 2.8
Bishop's Stortford: 5.0
Bondleigh: 5.0
Borehamwood: 4.8
Boughton Monchelsea: 5.0
Bournemouth: 4.8
Bradley Stoke: 5.0
Brecon: 4.8
Brent: 4.5
Brentford: 4.7
Brentwood: 4.8
Bricket Wood: 4.9
Bridford: 5.0
Brighton: 4.5
Bristol: 4.8
Bromley: 4.8
Brookwood: 4.6
Buckhurst Hill: 5.0
Burnham: 4.8
Burntwood: 5.0
Buscot: 4.5
Bushey: 5.0
Butterleigh: 5.0
Buxton: 5.0
Cambridge: 4.0
Camden Town: 4.7
Canterbury: 4.9
Capel Isaac: 5.0
Cardiff: 4.9
Carshalton: 4.8
Caterham: 5.0
Chaldon: 4.7
Chelmsford: 4.3
Chertsey: 5.0
Chester: 5.0
Chestfield: 5.0
Chichester: 5.0
Chiddingfold: 5.0
Chigwell: 4.8
Child Okeford: 4.8
Chislehurst: 4.8
Chorleywood: 4.9
Cirencester: 4.5
Claygate: 4.9
Colchester: 4.8
College Town: 5.0
Cookham: 4.2
Cothelstone: 5.0
Coulsdon: 4.9
Coventry: 4.5
Cowdenbeath: 4.8
Coxley: 4.8
Cranbrook: 5.0
Crediton: 5.0
Crockenhill: 4.8
Crockerton: 4.9
Crostwick: 5.0
Croydon: 4.2
Cuffley: 4.9
Dagenham: 4.7
Dartford: 4.8
Delph: 5.0
Denham: 4.4
Denton: 5.0
Downe: 5.0
Dundee: 4.8
East Molesey: 4.9
Eastbourne: 5.0
Edgware: 4.8
Edinburgh: 4.6
Egerton: 4.8
Elstree: 5.0
Enfield: 4.8
Epsom: 4.6
Esher: 4.8
Ewell: 4.5
Exeter: 4.9
Fairwarp: 4.8
Farnborough: 4.9
Farnham: 4.9
Feltham: 4.9
Fetcham: 5.0
Findon: 4.8
Frittenden: 4.5
Frome: 5.0
Fyfield: 4.5
Gamston: 4.9
Giffnock: 4.7
Gillingham: 5.0
Glasgow: 5.0
Gloucester: 5.0
Goff's Oak: 5.0
Great Chesterford: 4.1
Great Milton: 5.0
Great Missenden: 4.7
Great Waltham: 5.0
Green Tye: 4.5
Greenford: 4.6
Gretton: 5.0
Guildford: 4.9
Guiseley: 4.8
Hackney: 4.8
Hagley: 5.0
Hammersmith: 4.9
Hampreston: 5.0
Hampton: 4.8
Hampton Hill: 5.0
Hampton Wick: 4.8
Hamstead Marshall: 5.0
Harefield: 5.0
Harlington: 4.7
Harrogate: 4.5
Harrow: 4.7
Hartland: 5.0
Hayes: 4.9
Hayle: 4.7
Hebden Bridge: 4.8
Herne Bay: 4.9
Hessle: 4.7
High Wycombe: 5.0
Hinton Ampner: 4.8
Hordle: 5.0
Horley: 4.9
Hornchurch: 4.9
Horsham: 4.7
Hounslow: 4.8
Hove: 4.4
Huddersfield: 5.0
Hull: 5.0
Huntington: 4.4
Hurst Green: 5.0
Hurstpierpoint: 5.0
Ickenham: 4.9
Ilford: 3.8
Instow: 4.9
Isleworth: 4.6
Islington: 4.7
Kendal: 5.0
Kensington: 4.8
Kingston upon Thames: 4.9
Kirdford: 5.0
Langley: 5.0
Leeds: 4.9
Leicester: 5.0
Linchmere: 5.0
Lindfield: 4.7
Linkenholt: 4.7
Little Ann: 5.0
Liverpool: 5.0
London: 4.8
Long Ditton: 4.9
Longford: 5.0
Loughborough: 4.7
Loughton: 4.9
Ludlow: 5.0
Luton: 4.5
Lymm: 5.0
Lyng: 4.9
Maidstone: 3.2
Manchester: 4.6
Margate: 5.0
Marlow: 4.3
Martlesham: 5.0
Mells: 4.3
Milton Keynes: 4.8
Mitcham: 4.9
Molesey: 4.9
Monxton: 4.9
Morden: 4.9
New Barnet: 4.9
New Malden: 4.6
Newbury: 4.8
Newcastle Upon Tyne: 4.0
Newcastle upon Tyne: 4.8
Newgale: 4.9
Northaw: 4.9
Northolt: 4.7
Northwood: 4.9
Norwich: 5.0
Nottingham: 4.8
Oakley: 5.0
Old Coulsdon: 4.9
Orpington: 4.9
Oxford: 4.7
Paddington: 4.9
Perivale: 4.7
Pinner: 4.8
Poole: 4.0
Potters Bar: 4.6
Prestwich: 4.9
Purleigh: 5.0
Purley: 4.9
Rainham: 5.0
Reading: 4.5
Reigate: 4.8
Richmond: 4.9
Rickmansworth: 4.9
Ripponden: 4.8
Roade: 4.8
Romford: 4.8
Royal Leamington Spa: 4.4
Royal Tunbridge Wells: 4.6
Ruddington: 4.7
Ruislip: 4.8
Rye: 5.0
Saint Albans: 5.0
Saint Leonards: 4.7
Saint Mary Bourne: 4.8
Salisbury: 5.0
Sandhurst: 5.0
Scawby: 4.8
Scotland: 5.0
Selsey: 4.8
Sevenoaks: 4.9
Shaftesbury: 5.0
Sheffield: 5.0
Shillington: 4.8
Shoreham-by-Sea: 5.0
Shrivenham: 5.0
Sidcup: 5.0
Skewen: 1.0
Slough: 4.9
Solihull: 4.9
Sompting: 5.0
South Croydon: 5.0
South Littleton: 5.0
South Ockendon: 5.0
Southall: 4.8
Southampton: 4.7
Southend-on-Sea: 4.9
St Albans: 4.8
St. Ives: 4.8
Staines-upon-Thames: 4.6
Stanwell: 5.0
Stapleford Abbotts: 5.0
Stelling Minnis: 5.0
Stirling: 5.0
Stockport: 4.8
Stratford: 4.9
Stratford-upon-Avon: 4.7
Sunbury: 5.0
Sunbury-on-Thames: 4.9
Sunninghill: 5.0
Surbiton: 4.9
Sutton: 4.8
Sutton Weaver: 5.0
Swansea: 5.0
Taplow: 4.9
Tatsfield: 4.8
Teddington: 4.9
Thames Ditton: 4.9
Thetford: 4.8
Thornton Heath: 4.5
Tibbermore: 5.0
Tilton on the Hill: 4.5
Tolleshunt D'Arcy: 4.7
Totnes: 5.0
Truro: 4.9
Tunworth: 4.8
Twickenham: 4.9
Upminster: 5.0
Upper Basildon: 4.7
Uxbridge: 4.8
Wales: 4.8
Wallington: 4.9
Waltham Abbey: 4.9
Walton-on-Thames: 4.7
Warlingham: 4.9
Watford: 4.9
Welling: 5.0
Wembley: 4.4
West Hyde: 4.9
West Molesey: 4.9
West Pennard: 4.9
West Wittering: 5.0
Westerham: 4.8
Weston Rhyn: 5.0
Weybridge: 4.7
Winchester: 4.4
Windsor: 4.4
Winterbourne: 5.0
Wolverton: 4.9
Woodford: 4.9
Worcester Park: 4.5
Wraysbury: 4.5
York: 4.6

In [39]:

# Get input from user for the location
location = input("Enter the location for which you want to calculate the average review scores rating: ").lower()

# Filter the data for the specified location
location_df = df[df['host_location'].str.lower() == location]

# Calculate the mean of review_scores_rating for the specified location
avg_rating = location_df['review_scores_rating'].mean()

# Print the average review scores rating for the specified location
print(f"Average review scores rating for {location.capitalize()}: {avg_rating:.1f}")

Enter the location for which you want to calculate the average review scores rating: london
Average review scores rating for London: 4.8

In [45]:
# Analyse to get insightful information based on your own selection
# Here's an example of randomly selecting 5 hosts and displaying their listing titles
random_hosts = df.sample(n=5)
print("Randomly selected hosts and their listing titles:")
for index, host in random_hosts.iterrows():
    print(f"- {host['host_name']}: {host['name']}: {host['host_location']}: {host['property_type']}")

Randomly selected hosts and their listing titles:
- Wojciech: Modern 2bed and breakfast flat with canal views: London: condo
- Sangeeta: Lovely room to let on the top floor flat: London: rental unit
- Tatiana: Lovely Cozy Studio Flat in South London: London: rental unit
- Paro: Ensuite with kitchenette Canary Wharf Isle of Dogs: London: rental unit
- Judita: Londoner's flat for comfortable stay: London: rental unit

In [47]:

# Get user input for number of hosts to randomly select
num_hosts = int(input("Enter the number of hosts to be randomly selected: "))

# Randomly select hosts and their listing titles
random_hosts = df.sample(n=num_hosts)
print(f"Randomly selected {num_hosts} hosts and their listing titles:")
for index, host in random_hosts.iterrows():
    print(f"-{host['host_name']}: {host['name']}: {host['bedrooms']}: {host['price']}: {host['number_of_reviews']}")

Enter the number of hosts to be randomly selected: 7
Randomly selected 7 hosts and their listing titles:
-Victor: London Central Single Room Victoria Station Zone 1: 1: 73: 45
-Vera: Bright and Clean Double Bedroom in Hackney: 1: 50: 12
-Ricardo Brizido Pass The Keys: Modern & Peaceful Family Home | Pass The Keys: 3: 229: 7
-Amanda: HEART OF CENTRAL LONDON PERFECT LOCATION IN STYLE: 1: 182: 4
-Alizee: Stylish & Quiet garden flat in Camden: 1: 186: 2
-Jimi: Beautiful and modern 2 BED FLAT in Zone 1: 2: 199: 36
-Savi: Landstead House (O2 & City Airport, Excel): 4: 186: 1